EXTRAKEY_ENABLE = yes
MOUSEKEY_ENABLE = yes
KEY_OVERRIDE_ENABLE = yes

VIA_ENABLE = yes

MAGIC_ENABLE = yes
CAPS_WORD_ENABLE = yes

# Pro Micro RP2040 features
CONVERT_TO = promicro_rp2040
RGBLIGHT_ENABLE = yes
RGBLIGHT_DRIVER = WS2812
WS2812_DRIVER = vendor
WS2812_DI_PIN = GPIO25
RGBLIGHT_LED_COUNT = 1
