EXTRAKEY_ENABLE = yes
MOUSEKEY_ENABLE = yes
TAP_DANCE_ENABLE = yes
KEY_OVERRIDE_ENABLE = yes

VIA_ENABLE = yes

MAGIC_ENABLE = yes
CAPS_WORD_ENABLE = yes

# Pro Micro RP2040 features
CONVERT_TO = promicro_rp2040
RGBLIGHT_ENABLE = yes

# OS Detection
OS_DETECTION_ENABLE = yes
